# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
