# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 13:09
from __future__ import unicode_literals

import complaints.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='ticket_id',
            field=models.CharField(default=complaints.models.generate_key, max_length=25),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
