# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 14:06
from __future__ import unicode_literals

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20180321_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='ticket_id',
            field=models.CharField(default=complaints.models.generate_key, max_length=25, unique=True),
        ),
    ]
