# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20180321_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='complaints',
            name='mail_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
