# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0005_auto_20180325_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_taken_by',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
